### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by Muftawo** [code-and-dogs/mqtt-python#3]
Can you help me understand what is happening here and how I can fix it. 
I run the same code but I keep getting a time-out error. 

`Traceback (most recent call last):
  File "mqtt_publish1.py", line 7, in <module>
    client.connect(mqttBroker, 1883 , 80)
  File "/Users/mufti/miniconda3/lib/python3.8/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/Users/mufti/miniconda3/lib/python3.8/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/Users/mufti/miniconda3/lib/python3.8/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/Users/mufti/miniconda3/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/mufti/miniconda3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)`

**Comment by tirthshah17** [comment]
Hi Muftawo,

I am encountering the same error. Were you able to resolve it later? Please let me know if you got an alternate solution to this.

Thanks,
Tirth
